version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /var/data/recs_db:/data/db
  nodejs:
    build:
      dockerfile: Dockerfile
    container_name: nodejs
    restart: unless-stopped
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=from_docker
      - RECS_ADDR=http://python:5000
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - python
  python:
    extends:
      file: ./RecommendationProject/docker-compose.yml
      service: flask
    ports:
      - 5000:5000